version: '3'

services:
  cfddns:
    image: cfddns
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN}
    secrets:
    - accountid
    - token

secrets:
  accountid:
    file: ./accountid
  token:
    file: ./token
