version: '3'

services:
  cfddns:
    image: cfddns
    environment:
      - DOMAIN=${DOMAIN}
      - SUBDOMAIN=${SUBDOMAIN}
      - EMAIL=${EMAIL}
    secrets:
    - accountid
    - globalkey

secrets:
  accountid:
    file: ./accountid
  globalkey:
    file: ./globalkey
